### PR TITLE
News week project 

### PR DESCRIPTION
**Pull request by Fanger53**
# News Week page with bootstrap 
This project consists of building a clone of the News weeks page, to understand the use of CSS frameworks, in this project we use bootstrap 4 frameworks for making the front-end of this web-site and we wanted to know how works the frameworks in differents electronic dispositive

### CODE REVIEW

**Review by bertil291utn — CHANGES_REQUESTED** [review]
# **Status:** Changes requested 🟠 
<p align="center"> image <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
## General requirements 

- [x] It's not necessary to show all screenshot pages, use this [mockup](https://www.mockupworld.co/free/responsive-web-design-showcase-mockup/)
- [x] Add links and title markdown syntax to the README file

Example:

```markdown

## Live demo
[Live Demo](Link:https://raw.githack.com/Fanger53/News-Week/features/index.html)
## Getting start

## Authors
[Github:](https://github.com/Fanger53)

[Twitter:](https://twitter.com/DavidLe97005129)

[Linkedin:](https://www.linkedin.com/in/david-castillo-61ba10b8/)

## Acknowledgment 
```

## Specific requirements 
| Section/Screen                             | Large | Medium | Small |
| :----------------------------------------- | :---: | :----: | :---: |
| Navbar              |  1,2    |  3,4    |       |
| Featured stories              |      |        |       |
| Top story             |       |        |       |
| My turn             |       |        |       |
| Cultural&Travel             |      |        |       |
| Opinion                 |       |        |       |
| Latest news                  |       |        |       |
| More stories |      |        |       |
| In the magazine         |       |        |       |
| Editor's pick |    |     |      |
| Footer                                     |       |   5,6,7     |       |
###### This table is given each section with his screen width approach, each issue is given by number below this table

(1) 

- [x] Add a transparent logo, to avoid a different red background 

(2)
- [x] Align the text according to the original page 

| ACTUAL WEB PAGE | YOURS |
| :-------------: | :---: |
| image | image |

(3) 
- [x] Remove right padding 
 
image

(4)
- [x] Logo should be aligned more to the right
image

(5)

- [x] Remove extra padding in the footer  

image

(6)
- [x] Align copyright section to the right 
image

(7)
- [x] Add a bottom padding
image


(8) Please fix the order for the small screen approach
**This is the correct order**
   - Top story
   - Featured stories
   - The debate
   - Opinion 
   - More Stories
   - My Turn
   -  Culture& Travel
   - In the magazine
   - Editor's pick
   - Footer

### Summary
- Please fix with small screens approach, check should be the same order as requested 
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

**Review by ghost — CHANGES_REQUESTED** [review]
Hello,
Great job on the project so far. However, there are some small issues to fix. 

### **General requirements**
1) Please fix the order of topics for the small screen.
**Here is the correct order**:

- Top story
- Featured stories
- The debate
- Opinion
- More Stories
- My Turn
- Culture& Travel
- In the magazine
- Editor's pick
- Footer

2) Remove the space below your navbar, for the small and medium screen sizes.

top-section-line

3) Add space for the Debate and Featured stories headlines on small and medium screen sizes.

Your webpage  |  Original webpage
----------------- | -------------------- 
featured_stories |  feature_stories_orig

Your webpage  |  Original webpage
----------------- | -------------------- 
debate | debate_orig

4) The design for the newsletter sign up box, on the right side of the page, breaks as you approach the 992px width. Please fix that.

sidebar_signup

5) On the readme file, you gave the wrong link to the original webpage.

### **Optional**

- Instead of using @githubhandle or @twitterhandle, on your readme author section, you can use your own username e.g @Fanger53. 

**Please make the requested changes and send another review. Good luck!**

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Comment by umairarshadbutt** [comment]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @hamayun-cpu AND @Fanger53 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly read below 👇 and work on the suggested changes.
- [x] Remove the space below your navbar, for the small and medium screen sizes. (Last TSE explained in her review with detail)
- [x] On the readme file, you gave the wrong link to the original webpage. (From the Last Review
- [x] Update the correct Live Link.

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Comment by umairarshadbutt** [comment]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://rawcdn.githack.com/Fanger53/News-Week/5f2bb371db587b51a34f6c1b86a7ff7c9cc2ab4a/index.html) shows a good understanding and usage of Bootstrap. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @hamayun-cpu and @Fanger53! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
